version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5101:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - MONGO_URI=mongodb://mongodb:27017/funeralapp
    depends_on:
      - mongodb
    restart: unless-stopped
    volumes:
      - backend-uploads:/app/uploads

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "3101:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://q14c5cff8kaukmncrx1w60rf.31.97.48.137.sslip.io
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

volumes:
  backend-uploads:
  mongodb-data:
