const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Template = require('./models/Template');

dotenv.config();

const MONGO_URI = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/funeral_post_maker';

const templatesData = [
  {
    "title": "Golden Floral Elegance",
    "category": "Floral",
    "status": "active",
    "width": 1080,
    "height": 1920,
    "background": {
      "type": "color",
      "value": "#1E252B"
    },
    "textLayers": [
      {
        "id": "1",
        "content": "In Loving Memory of",
        "fontFamily": "Georgia",
        "fontSize": 0.0741,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.1146,
        "width": 0.8148,
        "height": 0.0521,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "2",
        "content": "John Doe",
        "fontFamily": "Georgia",
        "fontSize": 0.1296,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.5521,
        "width": 0.8148,
        "height": 0.0729,
        "fontWeight": "bold",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "date",
        "content": "12.10.1950 - 24.06.2026",
        "fontFamily": "Inter",
        "fontSize": 0.0444,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.6458,
        "width": 0.8148,
        "height": 0.0417,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "message",
        "content": "You will always be in our hearts. Your love and wisdom guide us every single day.",
        "fontFamily": "Georgia",
        "fontSize": 0.0389,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.7083,
        "width": 0.8148,
        "height": 0.1875,
        "fontWeight": "normal",
        "fontStyle": "italic",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      }
    ],
    "imageLayers": [
      {
        "id": "flower_1",
        "type": "sticker",
        "url": "http://localhost:3000/flowers/floral_gold_leaves.png",
        "x": 0,
        "y": 0,
        "width": 1,
        "height": 0.5625,
        "rotation": 0,
        "opacity": 1,
        "mixBlendMode": "multiply",
        "visible": true
      },
      {
        "id": "3",
        "type": "frame",
        "url": "",
        "maskShape": "rounded_rect",
        "x": 0.2037,
        "y": 0.1875,
        "width": 0.5926,
        "height": 0.3333,
        "rotation": 0,
        "opacity": 1,
        "borderWidth": 0.0019,
        "borderColor": "#E6DEC9"
      }
    ],
    "shapeLayers": []
  },
  {
    "title": "Serene Sunset & Doves",
    "category": "Peaceful",
    "status": "active",
    "width": 1080,
    "height": 1920,
    "background": {
      "type": "color",
      "value": "#FDFBF7"
    },
    "textLayers": [
      {
        "id": "1",
        "content": "CELEBRATING THE LIFE OF",
        "fontFamily": "Inter",
        "fontSize": 0.0741,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.1146,
        "width": 0.8148,
        "height": 0.0521,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "2",
        "content": "John Doe",
        "fontFamily": "Georgia",
        "fontSize": 0.1296,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.5521,
        "width": 0.8148,
        "height": 0.0729,
        "fontWeight": "bold",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "date",
        "content": "October 12, 1950 - June 24, 2026",
        "fontFamily": "Inter",
        "fontSize": 0.0444,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.6458,
        "width": 0.8148,
        "height": 0.0417,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "message",
        "content": "Those we love don't go away, they walk beside us every day. Unseen, unheard, but always near, still loved, still missed and very dear.",
        "fontFamily": "Inter",
        "fontSize": 0.0389,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.7083,
        "width": 0.8148,
        "height": 0.1875,
        "fontWeight": "normal",
        "fontStyle": "italic",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      }
    ],
    "imageLayers": [
      {
        "id": "flower_2",
        "type": "sticker",
        "url": "http://localhost:3000/flowers/floral_cherry_blossom.png",
        "x": 0,
        "y": 0,
        "width": 1,
        "height": 0.5625,
        "rotation": 0,
        "opacity": 1,
        "mixBlendMode": "multiply",
        "visible": true
      },
      {
        "id": "3",
        "type": "frame",
        "url": "",
        "maskShape": "circle",
        "x": 0.2037,
        "y": 0.1875,
        "width": 0.5926,
        "height": 0.3333,
        "rotation": 0,
        "opacity": 1,
        "borderWidth": 0.0037,
        "borderColor": "#FFFFFF"
      }
    ],
    "shapeLayers": []
  },
  {
    "title": "Sacred Cross & Sunlight",
    "category": "Spiritual",
    "status": "active",
    "width": 1080,
    "height": 1920,
    "background": {
      "type": "color",
      "value": "#E8ECEF"
    },
    "textLayers": [
      {
        "id": "1",
        "content": "Rest in Peace",
        "fontFamily": "Georgia",
        "fontSize": 0.0741,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.1146,
        "width": 0.8148,
        "height": 0.0521,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "2",
        "content": "John Doe",
        "fontFamily": "Georgia",
        "fontSize": 0.1296,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.5521,
        "width": 0.8148,
        "height": 0.0729,
        "fontWeight": "bold",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "date",
        "content": "1950 - 2026",
        "fontFamily": "Inter",
        "fontSize": 0.0444,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.6458,
        "width": 0.8148,
        "height": 0.0417,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "message",
        "content": "May the Lord wrap you in His loving embrace. Rest in eternal peace, in the kingdom of heaven.",
        "fontFamily": "Georgia",
        "fontSize": 0.0389,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.7083,
        "width": 0.8148,
        "height": 0.1875,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      }
    ],
    "imageLayers": [
      {
        "id": "flower_3",
        "type": "sticker",
        "url": "http://localhost:3000/flowers/floral_forget_me_not.png",
        "x": 0,
        "y": 0,
        "width": 1,
        "height": 0.5625,
        "rotation": 0,
        "opacity": 1,
        "mixBlendMode": "multiply",
        "visible": true
      },
      {
        "id": "3",
        "type": "frame",
        "url": "",
        "maskShape": "rounded_rect",
        "x": 0.2037,
        "y": 0.1875,
        "width": 0.5926,
        "height": 0.3333,
        "rotation": 0,
        "opacity": 1,
        "borderWidth": 0.0019,
        "borderColor": "#E6DEC9"
      }
    ],
    "shapeLayers": []
  },
  {
    "title": "Classic Rose Garden",
    "category": "Floral",
    "status": "active",
    "width": 1080,
    "height": 1920,
    "background": {
      "type": "color",
      "value": "#1E252B"
    },
    "textLayers": [
      {
        "id": "1",
        "content": "In Loving Memory",
        "fontFamily": "Georgia",
        "fontSize": 0.0741,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.1146,
        "width": 0.8148,
        "height": 0.0521,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "2",
        "content": "Jane Doe",
        "fontFamily": "Georgia",
        "fontSize": 0.1296,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.5521,
        "width": 0.8148,
        "height": 0.0729,
        "fontWeight": "bold",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "date",
        "content": "1950 - 2026",
        "fontFamily": "Inter",
        "fontSize": 0.0444,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.6458,
        "width": 0.8148,
        "height": 0.0417,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "message",
        "content": "A life so beautifully lived deserves to be beautifully remembered. Your sweetness and kind spirit will bloom forever in our hearts.",
        "fontFamily": "Georgia",
        "fontSize": 0.0389,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.7083,
        "width": 0.8148,
        "height": 0.1875,
        "fontWeight": "normal",
        "fontStyle": "italic",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      }
    ],
    "imageLayers": [
      {
        "id": "flower_4",
        "type": "sticker",
        "url": "http://localhost:3000/flowers/floral_white_roses.png",
        "x": 0,
        "y": 0,
        "width": 1,
        "height": 0.5625,
        "rotation": 0,
        "opacity": 1,
        "mixBlendMode": "multiply",
        "visible": true
      },
      {
        "id": "3",
        "type": "frame",
        "url": "",
        "maskShape": "circle",
        "x": 0.2037,
        "y": 0.1875,
        "width": 0.5926,
        "height": 0.3333,
        "rotation": 0,
        "opacity": 1,
        "borderWidth": 0.0028,
        "borderColor": "#8F5D6B"
      }
    ],
    "shapeLayers": []
  },
  {
    "title": "Lily & Forget-me-not Serenity",
    "category": "Floral",
    "status": "active",
    "width": 1080,
    "height": 1920,
    "background": {
      "type": "color",
      "value": "#FFFFFF"
    },
    "textLayers": [
      {
        "id": "1",
        "content": "In Loving Memory of",
        "fontFamily": "Inter",
        "fontSize": 0.0741,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.1146,
        "width": 0.8148,
        "height": 0.0521,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "2",
        "content": "Jane Doe",
        "fontFamily": "Georgia",
        "fontSize": 0.1296,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.5521,
        "width": 0.8148,
        "height": 0.0729,
        "fontWeight": "bold",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "date",
        "content": "October 12, 1950 - June 24, 2026",
        "fontFamily": "Inter",
        "fontSize": 0.0444,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.6458,
        "width": 0.8148,
        "height": 0.0417,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "message",
        "content": "Forever loved, never forgotten. Your gentle soul brought sunshine and flowers into our lives. Rest in sweet peace.",
        "fontFamily": "Inter",
        "fontSize": 0.0389,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.7083,
        "width": 0.8148,
        "height": 0.1875,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      }
    ],
    "imageLayers": [
      {
        "id": "flower_5",
        "type": "sticker",
        "url": "http://localhost:3000/flowers/floral_lavender.png",
        "x": 0,
        "y": 0,
        "width": 1,
        "height": 0.5625,
        "rotation": 0,
        "opacity": 1,
        "mixBlendMode": "multiply",
        "visible": true
      },
      {
        "id": "3",
        "type": "frame",
        "url": "",
        "maskShape": "rounded_rect",
        "x": 0.2037,
        "y": 0.1875,
        "width": 0.5926,
        "height": 0.3333,
        "rotation": 0,
        "opacity": 1,
        "borderWidth": 0.0019,
        "borderColor": "#CBD5E1"
      }
    ],
    "shapeLayers": []
  },
  {
    "title": "Peaceful Ocean Shore",
    "category": "Peaceful",
    "status": "active",
    "width": 1080,
    "height": 1920,
    "background": {
      "type": "color",
      "value": "#1E252B"
    },
    "textLayers": [
      {
        "id": "1",
        "content": "CELEBRATING A BEAUTIFUL LIFE",
        "fontFamily": "Inter",
        "fontSize": 0.0741,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.1146,
        "width": 0.8148,
        "height": 0.0521,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "2",
        "content": "John Doe",
        "fontFamily": "Georgia",
        "fontSize": 0.1296,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.5521,
        "width": 0.8148,
        "height": 0.0729,
        "fontWeight": "bold",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "date",
        "content": "1950 - 2026",
        "fontFamily": "Inter",
        "fontSize": 0.0444,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.6458,
        "width": 0.8148,
        "height": 0.0417,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "message",
        "content": "Like the waves on the shore, your memory will always wash over us with peace and love. Sail on, beautiful soul, into eternal tranquility.",
        "fontFamily": "Inter",
        "fontSize": 0.0389,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.7083,
        "width": 0.8148,
        "height": 0.1875,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      }
    ],
    "imageLayers": [
      {
        "id": "flower_6",
        "type": "sticker",
        "url": "http://localhost:3000/flowers/floral_peonies.png",
        "x": 0,
        "y": 0,
        "width": 1,
        "height": 0.5625,
        "rotation": 0,
        "opacity": 1,
        "mixBlendMode": "multiply",
        "visible": true
      },
      {
        "id": "3",
        "type": "frame",
        "url": "",
        "maskShape": "circle",
        "x": 0.2037,
        "y": 0.1875,
        "width": 0.5926,
        "height": 0.3333,
        "rotation": 0,
        "opacity": 1,
        "borderWidth": 0.0037,
        "borderColor": "#E2E8F0"
      }
    ],
    "shapeLayers": []
  },
  {
    "title": "Autumn Remembrance",
    "category": "Classic",
    "status": "active",
    "width": 1080,
    "height": 1920,
    "background": {
      "type": "color",
      "value": "#FDFBF7"
    },
    "textLayers": [
      {
        "id": "1",
        "content": "In Loving Memory",
        "fontFamily": "Georgia",
        "fontSize": 0.0741,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.1146,
        "width": 0.8148,
        "height": 0.0521,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "2",
        "content": "John Doe",
        "fontFamily": "Georgia",
        "fontSize": 0.1296,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.5521,
        "width": 0.8148,
        "height": 0.0729,
        "fontWeight": "bold",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "date",
        "content": "1950 - 2026",
        "fontFamily": "Inter",
        "fontSize": 0.0444,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.6458,
        "width": 0.8148,
        "height": 0.0417,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "message",
        "content": "Autumn is a second spring where every leaf is a flower. Your life was rich with golden moments, and you will forever stay in our golden memories.",
        "fontFamily": "Georgia",
        "fontSize": 0.0389,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.7083,
        "width": 0.8148,
        "height": 0.1875,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      }
    ],
    "imageLayers": [
      {
        "id": "flower_7",
        "type": "sticker",
        "url": "http://localhost:3000/flowers/floral_ferns_corner.png",
        "x": 0,
        "y": 0,
        "width": 1,
        "height": 0.5625,
        "rotation": 0,
        "opacity": 1,
        "mixBlendMode": "multiply",
        "visible": true
      },
      {
        "id": "3",
        "type": "frame",
        "url": "",
        "maskShape": "rounded_rect",
        "x": 0.2037,
        "y": 0.1875,
        "width": 0.5926,
        "height": 0.3333,
        "rotation": 0,
        "opacity": 1,
        "borderWidth": 0.0019,
        "borderColor": "#E6DEC9"
      }
    ],
    "shapeLayers": []
  },
  {
    "title": "Heavenly Light",
    "category": "Peaceful",
    "status": "active",
    "width": 1080,
    "height": 1920,
    "background": {
      "type": "color",
      "value": "#1E252B"
    },
    "textLayers": [
      {
        "id": "1",
        "content": "Gone But Never Forgotten",
        "fontFamily": "Inter",
        "fontSize": 0.0741,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.1146,
        "width": 0.8148,
        "height": 0.0521,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "2",
        "content": "Jane Doe",
        "fontFamily": "Georgia",
        "fontSize": 0.1296,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.5521,
        "width": 0.8148,
        "height": 0.0729,
        "fontWeight": "bold",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "date",
        "content": "October 12, 1950 - June 24, 2026",
        "fontFamily": "Inter",
        "fontSize": 0.0444,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.6458,
        "width": 0.8148,
        "height": 0.0417,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "message",
        "content": "You left us beautiful memories, your love is still our guide, and though we cannot see you, you are always by our side.",
        "fontFamily": "Inter",
        "fontSize": 0.0389,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.7083,
        "width": 0.8148,
        "height": 0.1875,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      }
    ],
    "imageLayers": [
      {
        "id": "flower_8",
        "type": "sticker",
        "url": "http://localhost:3000/flowers/floral_lilies_frame.png",
        "x": 0,
        "y": 0,
        "width": 1,
        "height": 0.5625,
        "rotation": 0,
        "opacity": 1,
        "mixBlendMode": "multiply",
        "visible": true
      },
      {
        "id": "3",
        "type": "frame",
        "url": "",
        "maskShape": "circle",
        "x": 0.2037,
        "y": 0.1875,
        "width": 0.5926,
        "height": 0.3333,
        "rotation": 0,
        "opacity": 1,
        "borderWidth": 0.0028,
        "borderColor": "#E2E8F0"
      }
    ],
    "shapeLayers": []
  },
  {
    "title": "Forest Pine Serenity",
    "category": "Peaceful",
    "status": "active",
    "width": 1080,
    "height": 1920,
    "background": {
      "type": "color",
      "value": "#F8F5F2"
    },
    "textLayers": [
      {
        "id": "1",
        "content": "Celebrating the Life of",
        "fontFamily": "Inter",
        "fontSize": 0.0741,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.1146,
        "width": 0.8148,
        "height": 0.0521,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "2",
        "content": "John Doe",
        "fontFamily": "Georgia",
        "fontSize": 0.1296,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.5521,
        "width": 0.8148,
        "height": 0.0729,
        "fontWeight": "bold",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "date",
        "content": "1950 - 2026",
        "fontFamily": "Inter",
        "fontSize": 0.0444,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.6458,
        "width": 0.8148,
        "height": 0.0417,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "message",
        "content": "Quiet, peaceful, and strong—like the pine forests you loved. Your legacy stands tall in our family, and your peace is now eternal.",
        "fontFamily": "Inter",
        "fontSize": 0.0389,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.7083,
        "width": 0.8148,
        "height": 0.1875,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      }
    ],
    "imageLayers": [
      {
        "id": "flower_9",
        "type": "sticker",
        "url": "http://localhost:3000/flowers/floral_olive_branch.png",
        "x": 0,
        "y": 0,
        "width": 1,
        "height": 0.5625,
        "rotation": 0,
        "opacity": 1,
        "mixBlendMode": "multiply",
        "visible": true
      },
      {
        "id": "3",
        "type": "frame",
        "url": "",
        "maskShape": "rounded_rect",
        "x": 0.2037,
        "y": 0.1875,
        "width": 0.5926,
        "height": 0.3333,
        "rotation": 0,
        "opacity": 1,
        "borderWidth": 0.0019,
        "borderColor": "#D1FAE5"
      }
    ],
    "shapeLayers": []
  },
  {
    "title": "Cherry Blossom & Carnation Grace",
    "category": "Floral",
    "status": "active",
    "width": 1080,
    "height": 1920,
    "background": {
      "type": "color",
      "value": "#1E252B"
    },
    "textLayers": [
      {
        "id": "1",
        "content": "Rest in Eternal Peace",
        "fontFamily": "Georgia",
        "fontSize": 0.0741,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.1146,
        "width": 0.8148,
        "height": 0.0521,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "2",
        "content": "Jane Doe",
        "fontFamily": "Georgia",
        "fontSize": 0.1296,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.5521,
        "width": 0.8148,
        "height": 0.0729,
        "fontWeight": "bold",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "date",
        "content": "12.10.1950 - 24.06.2026",
        "fontFamily": "Inter",
        "fontSize": 0.0444,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.6458,
        "width": 0.8148,
        "height": 0.0417,
        "fontWeight": "normal",
        "fontStyle": "normal",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      },
      {
        "id": "message",
        "content": "Your memory is a keepsake from which we will never part. God has you in His keeping, we have you in our hearts.",
        "fontFamily": "Georgia",
        "fontSize": 0.0389,
        "color": "#FFFFFF",
        "alignment": "center",
        "x": 0.0926,
        "y": 0.7083,
        "width": 0.8148,
        "height": 0.1875,
        "fontWeight": "normal",
        "fontStyle": "italic",
        "textDecoration": "none",
        "opacity": 1,
        "rotation": 0,
        "hasShadow": true,
        "shadowColor": "rgba(0,0,0,0.6)",
        "shadowBlur": 0.0074
      }
    ],
    "imageLayers": [
      {
        "id": "flower_10",
        "type": "sticker",
        "url": "http://localhost:3000/flowers/floral_daisy_divider.png",
        "x": 0,
        "y": 0,
        "width": 1,
        "height": 0.5625,
        "rotation": 0,
        "opacity": 1,
        "mixBlendMode": "multiply",
        "visible": true
      },
      {
        "id": "3",
        "type": "frame",
        "url": "",
        "maskShape": "circle",
        "x": 0.2037,
        "y": 0.1875,
        "width": 0.5926,
        "height": 0.3333,
        "rotation": 0,
        "opacity": 1,
        "borderWidth": 0.0028,
        "borderColor": "#FCE7F3"
      }
    ],
    "shapeLayers": []
  }
];

async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("Seeder: Connected to MongoDB successfully.");
    
    // Clear out active templates to prevent duplicates
    await Template.deleteMany({ status: 'active' });
    console.log("Seeder: Cleared active templates.");
    
    await Template.insertMany(templatesData);
    console.log("Seeder: Successfully inserted 10 customizable templates!");
    
    mongoose.connection.close();
    console.log("Seeder: Connection closed.");
    process.exit(0);
  } catch (err) {
    console.error("Seeder failed:", err);
    process.exit(1);
  }
}

seed();
