const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Template = require('./models/Template');

dotenv.config();

const MONGO_URI = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/funeral_post_maker';

const templatesData = [
  {
    title: "Golden Floral Elegance",
    category: "Floral",
    status: "active",
    width: 1080,
    height: 1920,
    background: {
      type: "image",
      value: "http://127.0.0.1:5001/uploads/design_1.png"
    },
    textLayers: [
      {
        id: "1",
        content: "In Loving Memory of",
        fontFamily: "Georgia",
        fontSize: 80,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 220,
        width: 880,
        height: 100,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "2",
        content: "John Doe",
        fontFamily: "Georgia",
        fontSize: 140,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1060,
        width: 880,
        height: 140,
        fontWeight: "bold",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "date",
        content: "12.10.1950 - 24.06.2026",
        fontFamily: "Inter",
        fontSize: 48,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1240,
        width: 880,
        height: 80,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "message",
        content: "You will always be in our hearts. Your love and wisdom guide us every single day.",
        fontFamily: "Georgia",
        fontSize: 42,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1360,
        width: 880,
        height: 360,
        fontWeight: "normal",
        fontStyle: "italic",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      }
    ],
    imageLayers: [
      {
        id: "3",
        type: "frame",
        url: "",
        maskShape: "rounded_rect",
        x: 220,
        y: 360,
        width: 640,
        height: 640,
        rotation: 0,
        opacity: 1,
        borderWidth: 2,
        borderColor: "#E6DEC9"
      }
    ],
    shapeLayers: []
  },
  {
    title: "Serene Sunset & Doves",
    category: "Peaceful",
    status: "active",
    width: 1080,
    height: 1920,
    background: {
      type: "image",
      value: "http://127.0.0.1:5001/uploads/design_2.png"
    },
    textLayers: [
      {
        id: "1",
        content: "CELEBRATING THE LIFE OF",
        fontFamily: "Inter",
        fontSize: 80,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 220,
        width: 880,
        height: 100,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "2",
        content: "John Doe",
        fontFamily: "Georgia",
        fontSize: 140,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1060,
        width: 880,
        height: 140,
        fontWeight: "bold",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "date",
        content: "October 12, 1950 - June 24, 2026",
        fontFamily: "Inter",
        fontSize: 48,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1240,
        width: 880,
        height: 80,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "message",
        content: "Those we love don't go away, they walk beside us every day. Unseen, unheard, but always near, still loved, still missed and very dear.",
        fontFamily: "Inter",
        fontSize: 42,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1360,
        width: 880,
        height: 360,
        fontWeight: "normal",
        fontStyle: "italic",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      }
    ],
    imageLayers: [
      {
        id: "3",
        type: "frame",
        url: "",
        maskShape: "circle",
        x: 220,
        y: 360,
        width: 640,
        height: 640,
        rotation: 0,
        opacity: 1,
        borderWidth: 4,
        borderColor: "#FFFFFF"
      }
    ],
    shapeLayers: []
  },
  {
    title: "Sacred Cross & Sunlight",
    category: "Spiritual",
    status: "active",
    width: 1080,
    height: 1920,
    background: {
      type: "image",
      value: "http://127.0.0.1:5001/uploads/design_3.png"
    },
    textLayers: [
      {
        id: "1",
        content: "Rest in Peace",
        fontFamily: "Georgia",
        fontSize: 80,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 220,
        width: 880,
        height: 100,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "2",
        content: "John Doe",
        fontFamily: "Georgia",
        fontSize: 140,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1060,
        width: 880,
        height: 140,
        fontWeight: "bold",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "date",
        content: "1950 - 2026",
        fontFamily: "Inter",
        fontSize: 48,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1240,
        width: 880,
        height: 80,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "message",
        content: "May the Lord wrap you in His loving embrace. Rest in eternal peace, in the kingdom of heaven.",
        fontFamily: "Georgia",
        fontSize: 42,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1360,
        width: 880,
        height: 360,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      }
    ],
    imageLayers: [
      {
        id: "3",
        type: "frame",
        url: "",
        maskShape: "rounded_rect",
        x: 220,
        y: 360,
        width: 640,
        height: 640,
        rotation: 0,
        opacity: 1,
        borderWidth: 2,
        borderColor: "#E6DEC9"
      }
    ],
    shapeLayers: []
  },
  {
    title: "Classic Rose Garden",
    category: "Floral",
    status: "active",
    width: 1080,
    height: 1920,
    background: {
      type: "image",
      value: "http://127.0.0.1:5001/uploads/design_4.png"
    },
    textLayers: [
      {
        id: "1",
        content: "In Loving Memory",
        fontFamily: "Georgia",
        fontSize: 80,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 220,
        width: 880,
        height: 100,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "2",
        content: "Jane Doe",
        fontFamily: "Georgia",
        fontSize: 140,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1060,
        width: 880,
        height: 140,
        fontWeight: "bold",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "date",
        content: "1950 - 2026",
        fontFamily: "Inter",
        fontSize: 48,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1240,
        width: 880,
        height: 80,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "message",
        content: "A life so beautifully lived deserves to be beautifully remembered. Your sweetness and kind spirit will bloom forever in our hearts.",
        fontFamily: "Georgia",
        fontSize: 42,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1360,
        width: 880,
        height: 360,
        fontWeight: "normal",
        fontStyle: "italic",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      }
    ],
    imageLayers: [
      {
        id: "3",
        type: "frame",
        url: "",
        maskShape: "circle",
        x: 220,
        y: 360,
        width: 640,
        height: 640,
        rotation: 0,
        opacity: 1,
        borderWidth: 3,
        borderColor: "#8F5D6B"
      }
    ],
    shapeLayers: []
  },
  {
    title: "Lily & Forget-me-not Serenity",
    category: "Floral",
    status: "active",
    width: 1080,
    height: 1920,
    background: {
      type: "image",
      value: "http://127.0.0.1:5001/uploads/design_5.png"
    },
    textLayers: [
      {
        id: "1",
        content: "In Loving Memory of",
        fontFamily: "Inter",
        fontSize: 80,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 220,
        width: 880,
        height: 100,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "2",
        content: "Jane Doe",
        fontFamily: "Georgia",
        fontSize: 140,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1060,
        width: 880,
        height: 140,
        fontWeight: "bold",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "date",
        content: "October 12, 1950 - June 24, 2026",
        fontFamily: "Inter",
        fontSize: 48,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1240,
        width: 880,
        height: 80,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "message",
        content: "Forever loved, never forgotten. Your gentle soul brought sunshine and flowers into our lives. Rest in sweet peace.",
        fontFamily: "Inter",
        fontSize: 42,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1360,
        width: 880,
        height: 360,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      }
    ],
    imageLayers: [
      {
        id: "3",
        type: "frame",
        url: "",
        maskShape: "rounded_rect",
        x: 220,
        y: 360,
        width: 640,
        height: 640,
        rotation: 0,
        opacity: 1,
        borderWidth: 2,
        borderColor: "#CBD5E1"
      }
    ],
    shapeLayers: []
  },
  {
    title: "Peaceful Ocean Shore",
    category: "Peaceful",
    status: "active",
    width: 1080,
    height: 1920,
    background: {
      type: "image",
      value: "http://127.0.0.1:5001/uploads/design_6.png"
    },
    textLayers: [
      {
        id: "1",
        content: "CELEBRATING A BEAUTIFUL LIFE",
        fontFamily: "Inter",
        fontSize: 80,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 220,
        width: 880,
        height: 100,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "2",
        content: "John Doe",
        fontFamily: "Georgia",
        fontSize: 140,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1060,
        width: 880,
        height: 140,
        fontWeight: "bold",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "date",
        content: "1950 - 2026",
        fontFamily: "Inter",
        fontSize: 48,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1240,
        width: 880,
        height: 80,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "message",
        content: "Like the waves on the shore, your memory will always wash over us with peace and love. Sail on, beautiful soul, into eternal tranquility.",
        fontFamily: "Inter",
        fontSize: 42,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1360,
        width: 880,
        height: 360,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      }
    ],
    imageLayers: [
      {
        id: "3",
        type: "frame",
        url: "",
        maskShape: "circle",
        x: 220,
        y: 360,
        width: 640,
        height: 640,
        rotation: 0,
        opacity: 1,
        borderWidth: 4,
        borderColor: "#E2E8F0"
      }
    ],
    shapeLayers: []
  },
  {
    title: "Autumn Remembrance",
    category: "Classic",
    status: "active",
    width: 1080,
    height: 1920,
    background: {
      type: "image",
      value: "http://127.0.0.1:5001/uploads/design_7.png"
    },
    textLayers: [
      {
        id: "1",
        content: "In Loving Memory",
        fontFamily: "Georgia",
        fontSize: 80,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 220,
        width: 880,
        height: 100,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "2",
        content: "John Doe",
        fontFamily: "Georgia",
        fontSize: 140,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1060,
        width: 880,
        height: 140,
        fontWeight: "bold",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "date",
        content: "1950 - 2026",
        fontFamily: "Inter",
        fontSize: 48,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1240,
        width: 880,
        height: 80,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "message",
        content: "Autumn is a second spring where every leaf is a flower. Your life was rich with golden moments, and you will forever stay in our golden memories.",
        fontFamily: "Georgia",
        fontSize: 42,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1360,
        width: 880,
        height: 360,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      }
    ],
    imageLayers: [
      {
        id: "3",
        type: "frame",
        url: "",
        maskShape: "rounded_rect",
        x: 220,
        y: 360,
        width: 640,
        height: 640,
        rotation: 0,
        opacity: 1,
        borderWidth: 2,
        borderColor: "#E6DEC9"
      }
    ],
    shapeLayers: []
  },
  {
    title: "Heavenly Light",
    category: "Peaceful",
    status: "active",
    width: 1080,
    height: 1920,
    background: {
      type: "image",
      value: "http://127.0.0.1:5001/uploads/design_8.png"
    },
    textLayers: [
      {
        id: "1",
        content: "Gone But Never Forgotten",
        fontFamily: "Inter",
        fontSize: 80,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 220,
        width: 880,
        height: 100,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "2",
        content: "Jane Doe",
        fontFamily: "Georgia",
        fontSize: 140,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1060,
        width: 880,
        height: 140,
        fontWeight: "bold",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "date",
        content: "October 12, 1950 - June 24, 2026",
        fontFamily: "Inter",
        fontSize: 48,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1240,
        width: 880,
        height: 80,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "message",
        content: "You left us beautiful memories, your love is still our guide, and though we cannot see you, you are always by our side.",
        fontFamily: "Inter",
        fontSize: 42,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1360,
        width: 880,
        height: 360,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      }
    ],
    imageLayers: [
      {
        id: "3",
        type: "frame",
        url: "",
        maskShape: "circle",
        x: 220,
        y: 360,
        width: 640,
        height: 640,
        rotation: 0,
        opacity: 1,
        borderWidth: 3,
        borderColor: "#E2E8F0"
      }
    ],
    shapeLayers: []
  },
  {
    title: "Forest Pine Serenity",
    category: "Peaceful",
    status: "active",
    width: 1080,
    height: 1920,
    background: {
      type: "image",
      value: "http://127.0.0.1:5001/uploads/design_9.png"
    },
    textLayers: [
      {
        id: "1",
        content: "Celebrating the Life of",
        fontFamily: "Inter",
        fontSize: 80,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 220,
        width: 880,
        height: 100,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "2",
        content: "John Doe",
        fontFamily: "Georgia",
        fontSize: 140,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1060,
        width: 880,
        height: 140,
        fontWeight: "bold",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "date",
        content: "1950 - 2026",
        fontFamily: "Inter",
        fontSize: 48,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1240,
        width: 880,
        height: 80,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "message",
        content: "Quiet, peaceful, and strong—like the pine forests you loved. Your legacy stands tall in our family, and your peace is now eternal.",
        fontFamily: "Inter",
        fontSize: 42,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1360,
        width: 880,
        height: 360,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      }
    ],
    imageLayers: [
      {
        id: "3",
        type: "frame",
        url: "",
        maskShape: "rounded_rect",
        x: 220,
        y: 360,
        width: 640,
        height: 640,
        rotation: 0,
        opacity: 1,
        borderWidth: 2,
        borderColor: "#D1FAE5"
      }
    ],
    shapeLayers: []
  },
  {
    title: "Cherry Blossom & Carnation Grace",
    category: "Floral",
    status: "active",
    width: 1080,
    height: 1920,
    background: {
      type: "image",
      value: "http://127.0.0.1:5001/uploads/design_10.png"
    },
    textLayers: [
      {
        id: "1",
        content: "Rest in Eternal Peace",
        fontFamily: "Georgia",
        fontSize: 80,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 220,
        width: 880,
        height: 100,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "2",
        content: "Jane Doe",
        fontFamily: "Georgia",
        fontSize: 140,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1060,
        width: 880,
        height: 140,
        fontWeight: "bold",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "date",
        content: "12.10.1950 - 24.06.2026",
        fontFamily: "Inter",
        fontSize: 48,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1240,
        width: 880,
        height: 80,
        fontWeight: "normal",
        fontStyle: "normal",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      },
      {
        id: "message",
        content: "Your memory is a keepsake from which we will never part. God has you in His keeping, we have you in our hearts.",
        fontFamily: "Georgia",
        fontSize: 42,
        color: "#FFFFFF",
        alignment: "center",
        x: 100,
        y: 1360,
        width: 880,
        height: 360,
        fontWeight: "normal",
        fontStyle: "italic",
        textDecoration: "none",
        opacity: 1,
        rotation: 0,
        hasShadow: true,
        shadowColor: "rgba(0,0,0,0.6)",
        shadowBlur: 8
      }
    ],
    imageLayers: [
      {
        id: "3",
        type: "frame",
        url: "",
        maskShape: "circle",
        x: 220,
        y: 360,
        width: 640,
        height: 640,
        rotation: 0,
        opacity: 1,
        borderWidth: 3,
        borderColor: "#FCE7F3"
      }
    ],
    shapeLayers: []
  }
];

async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("Seeder: Connected to MongoDB successfully.");
    
    // Clear out active templates to prevent duplicates
    await Template.deleteMany({ status: 'active' });
    console.log("Seeder: Cleared active templates.");
    
    await Template.insertMany(templatesData);
    console.log("Seeder: Successfully inserted 10 customizable templates!");
    
    mongoose.connection.close();
    console.log("Seeder: Connection closed.");
    process.exit(0);
  } catch (err) {
    console.error("Seeder failed:", err);
    process.exit(1);
  }
}

seed();
